loinc:
  release:
    default: '2.67'
    '2.67':
      version: '2.78'
      path: 'loinc_release/2.67' # runtime home directory-relative path
    '2.78':
      version:  '2.78'
      path: 'loinc_release/Loinc_2.78'

loinc_tree:
  release:
    default: '2.78'
    '2.78':
      tree_path: 'loinc_trees/2024-08-31'


snomed:
  release:
    default: 'INT_20240801'
    INT_20240801:
      files:
        description: 'snomed_release/SnomedCT_InternationalRF2_PRODUCTION_20240801T120000Z/Snapshot/Terminology/sct2_Description_Snapshot-en_INT_20240801.txt'
        relationship: 'snomed_release/SnomedCT_InternationalRF2_PRODUCTION_20240801T120000Z/Snapshot/Terminology/sct2_Relationship_Snapshot_INT_20240801.txt'

loinc_snomed:
  release:
    default: '20231015'
    '20231015':
      files:
        description: 'loinc_snomed_release/Snapshot/Terminology/xsct2_Description_Snapshot-en_LO1010000_20231015.txt'
        identifier: 'loinc_snomed_release/Snapshot/Terminology/xsct2_Identifier_Snapshot_LO1010000_20231015.txt'
        relationship: 'loinc_snomed_release/Snapshot/Terminology/xsct2_Relationship_Snapshot_LO1010000_20231015.txt'