loinc:
  release:
    default: '2.67'
    '2.67':
      version: '2.67'
      path: 'loinc_release/2.67' # runtime home directory-relative path

snomed:
  release:
    default: 'INT_20240801'
    INT_20240801:
      files:
        relationship: 'snomed_release/SnomedCT_InternationalRF2_PRODUCTION_20240801T120000Z/Snapshot/Terminology/sct2_Relationship_Snapshot_INT_20240801.txt'

