loinc:
  release:
    default: '2.67'
    '2.67':
      version: '2.67'
      path: 'loinc_release/2.67' # runtime home directory-relative path

snomed:
  release:
    default: 'INT_20240801'
    INT_20240801:
      files:
        description: 'snomed_release/SnomedCT_InternationalRF2_PRODUCTION_20240801T120000Z/Snapshot/Terminology/sct2_Description_Snapshot-en_INT_20240801.txt'
        relationship: 'snomed_release/SnomedCT_InternationalRF2_PRODUCTION_20240801T120000Z/Snapshot/Terminology/sct2_Relationship_Snapshot_INT_20240801.txt'

loinc_snomed:
  release:
    default: _20231015
    _20231015:
      files:
        description: 'loinc_snomed_release/Snapshot/Terminology/xsct2_Description_Snapshot-en_LO1010000_20231015.txt'
        identifier: 'loinc_snomed_release/Snapshot/Terminology/xsct2_Identifier_Snapshot_LO1010000_20231015.txt'
        relationship: 'loinc_snomed_release/Snapshot/Terminology/xsct2_Relationship_Snapshot_LO1010000_20231015.txt'