[tool.poetry]
name = "comp-loinc"
version = "0.1.0"
description = "Computable OWL Formalization of LOINC"
authors = ["Tim  Putman <putmantime@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
linkml = "^1.5.0"
linkml-owl = "^0.2.7"
typer = "^0.7.0"
pandas = "^2.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
