id: https://w3id.org/linkml/examples/chemicalinfo
name: chemicalinfo
prefixes:
  linkml: https://w3id.org/linkml/
  schema: http://schema.org/
  chemicalinfo: https://w3id.org/linkml/examples/chemicalinfo/
  LOINC: https://loinc.org/
imports:
  - linkml:types
default_curi_maps:
  - semweb_context
default_prefix: chemicalinfo
default_range: string

classes:
  LOINC:
    slots:
      - LOINCId
      - LOINCCode
      - LOINCName
      - has_part
    id_prefixes:
      - LOINC

#  Lipids:
#    is_a: Part
#  Porphyrins:
#    is_a: Part
#  MiscToxins:
#    is_a: Part
#  Arthropod:
#    is_a: Part
#  Microorganism:
#    is_a: Part

  Part:
    slots:
      - PartCode
      - PartName
      - part_type
      - part_of

  PartType:
    slots:
      - PartTypeCode
      - PartTypeName

  Container:
    slots:
      - LOINCData


slots:
  LOINCId:
    identifier: true
  LOINCCode:
    required: true
  LOINCName:
    required: true
  has_part:
    range: Part
    multivalued: true
    inlined: true
    inlined_as_list: true
  PartCode:
    required: true
  PartName:
    required: true
  part_type:
    range: PartType
    multivalued: true
    inlined: true
    inlined_as_list: true
  part_of:
    range: LOINC
    multivalued: true
    inlined: true
    inlined_as_list: true
  PartTypeCode:
    required: true
  PartTypeName:
    required: true
  LOINCData:
    range: LOINC
    multivalued: true
    inlined: true
    inlined_as_list: true

